---
title: "CS_09"
author: "Swetha"
date: "2024-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
data(world)
data(us_states)
```

```{r}
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"

storm_data <- read_csv(dataurl)
```

```{r}
head(storm_data)
```
```{r}
storm_data <- storm_data %>% 
  mutate(year=year(ISO_TIME)) 

storm_data <- storm_data %>%
  filter(year >= 1950)
storm_data <- storm_data %>%
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x))

```

```{r}
storm_data <- storm_data %>%
  mutate(decade =floor(year/10)*10)

storm_sf <- storm_data %>% 
  st_as_sf(coords=c("LON","LAT"),crs=4326)

region = st_bbox(storm_sf)
```

```{r}
ggplot() +
  geom_sf(data=world) +
  facet_wrap(~decade) +
  stat_bin2d(data = storm_sf,
    aes(y = st_coordinates(storm_sf)[, 2],x = st_coordinates(storm_sf)[, 1]),
    bins = 100) +
  scale_fill_distiller(palette = "YlOrRd",trans = "log",direction = -1,
                       breaks = c(1, 10, 100, 1000)) +
  coord_sf(xlim = region[c(1, 3)],ylim = region[c(2, 4)]) +
  theme_minimal()
```

```{r}
storm_crs = st_crs(storm_sf)
us_states_storm<- st_transform(us_states, crs = storm_crs)
us_states_name <- us_states_storm %>%
  select(state = NAME)
storm_states <- st_join(storm_sf, us_states_name, join = st_intersects, left = FALSE)
state_storms <- storm_states %>%
  group_by(state) %>%
  summarize(storms = length(unique(NAME))) %>%
  arrange(desc(storms)) %>%
  st_set_geometry(NULL)
top_5_states <- state_storms %>%
  slice(1:5)

knitr::kable(head(top_5_states))

```
