---
title: "CS_08 : Carbon Dioxide Concentrations at Mona Loa Observatory"
author: "SwethaSakhamuri"
format:
  html: default
  pptx: default
  gfm: default
  docx: default
editor: visual
execute:
  echo: false
  warning: false
  message: false
---

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(knitr)
library(kableExtra)

url <- "ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_annmean_mlo.txt"

co2_data <- read_table(
  url,
  skip = 34, # Skipping header lines
  col_names = c("Year", "MeanCO2", "Uncertainty"),
  comment = "#"
)
```

```{r}

ggplot(co2_data, aes(x = Year, y = MeanCO2)) +
  geom_line(color = "red", linewidth = 2) +
  labs(
    title="Annual Mean Carbon Dioxide Concentrations 1959-Present",
    x="Year",
    y="Mauna Loa Annual Mean CO2 Levels (ppm)"
  ) +
  theme_minimal()
```

```{r}
top_5 <- co2_data %>%
        arrange(desc(MeanCO2)) %>%
        head(5) %>%
        select(Year, MeanCO2)

top_5 %>%
  kable(caption = "Mauna Loa CO2 Annual Mean Data")

```
